### ISSUE TITLE
Export results in subsequent exceptions

### ISSUE THREAD

**Issue by co-stig** [flowkeeper-org/fk-desktop#21]
To reproduce, login into a websocket event source and export. Then try to execute any strategies -- this seems to generate events in the event source cloned for the export. Need to make sure the cloned event source is disconnected and purged properly.

```
Traceback (most recent call last):
  File "/home/w/projects/fk-desktop/src/fk/qt/qt_invoker.py", line 30, in event
    e.fn(**e.kwargs)
  File "/home/w/projects/fk-desktop/src/fk/core/import_export.py", line 257, in <lambda>
    lambda strategy, auto, **kwargs: None if auto else _export_message_processed(source,
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/w/projects/fk-desktop/src/fk/core/import_export.py", line 50, in _export_message_processed
    export_file.write(f'{serialized}\n')
ValueError: I/O operation on closed file.
```

**Comment by co-stig** [comment]
Fixed in 0.6.x.
