### ISSUE TITLE
Unhandled IndexError when selecting Settings

### ISSUE THREAD

**Issue by sagb** [flowkeeper-org/fk-desktop#38]
When selecting "Settings" from the menu or pressing F10, flowkeeper displays an error dialog.
Deleting the ~/.config/flowkeeper directory does not resolve the issue.

```
Traceback (most recent call last):
  File "fk/qt/actions.py", line 72, in <lambda>
  File "fk/qt/actions.py", line 81, in _call
  File "fk/desktop/application.py", line 392, in show_settings_dialog
  File "fk/desktop/settings.py", line 77, in __init__
  File "fk/desktop/settings.py", line 172, in _recompute_visibility
  File "fk/desktop/settings.py", line 151, in _computed_values
  File "fk/desktop/settings.py", line 301, in <lambda>
IndexError: list index out of range
```

**Comment by co-stig** [comment]
The likely cause is a missing audio device. Flowkeeper expected to find at least one output device to fill the "audio outputs" dropdown in Settings. This is fixed in 0.9.0 (#57).
